/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreaQuery: typeof import('./src/components/pages/ExportModule/dataDisplay/queryArea/AreaQuery.vue')['default']
    BaseHeader: typeof import('./src/components/layouts/BaseHeader.vue')['default']
    BaseMain: typeof import('./src/components/layouts/BaseMain/BaseMain.vue')['default']
    BaseSide: typeof import('./src/components/layouts/BaseSide.vue')['default']
    BatchQuery: typeof import('./src/components/pages/ExportModule/dataDisplay/queryArea/BatchQuery.vue')['default']
    CheckBtn: typeof import('./src/components/pages/deployModule/checkStep/checkBtn/index.vue')['default']
    CheckStep: typeof import('./src/components/pages/deployModule/checkStep/index.vue')['default']
    DataDisplay: typeof import('./src/components/pages/ExportModule/dataDisplay/index.vue')['default']
    DeployDisplay: typeof import('./src/components/pages/deployModule/checkStep/deployDisplay/index.vue')['default']
    DeployMenu: typeof import('./src/components/pages/deployModule/checkStep/deployMenu/index.vue')['default']
    DeployModule: typeof import('./src/components/pages/deployModule/index.vue')['default']
    DeployOverview: typeof import('./src/components/pages/deployModule/checkStep/deployOverview/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ExportModule: typeof import('./src/components/pages/ExportModule/index.vue')['default']
    GenerateStep: typeof import('./src/components/pages/deployModule/generateStep/index.vue')['default']
    ImportModule: typeof import('./src/components/pages/importModule/index.vue')['default']
    MainContent: typeof import('./src/components/layouts/BaseMain/MainContent.vue')['default']
    ModifyModule: typeof import('./src/components/pages/ModifyModule.vue')['default']
    MyPagination: typeof import('./src/components/common/myPagination/MyPagination.vue')['default']
    NodeSelect: typeof import('./src/components/pages/deployModule/prepareStep/nodeSelect/index.vue')['default']
    Overview: typeof import('./src/components/pages/ExportModule/overview/index.vue')['default']
    Pack: typeof import('./src/components/pages/ExportModule/pack/index.vue')['default']
    PrepareStep: typeof import('./src/components/pages/deployModule/prepareStep/index.vue')['default']
    ProjectSelect: typeof import('./src/components/common/projectSelect/index.vue')['default']
    QueryArea: typeof import('./src/components/pages/ExportModule/dataDisplay/queryArea/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepMenu: typeof import('./src/components/pages/deployModule/stepMenu/index.vue')['default']
    TitleBar: typeof import('./src/components/layouts/BaseMain/TitleBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
